name: arklib CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Build ArkLib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check
        run: cargo check

      - name: Format
        run: |
          cargo fmt --all -- --check
          cargo clippy

      - name: Build Debug
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build Release
        run: cargo build --verbose --release

  run_benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and run benchmarks
        run: cargo bench --verbose
