name: Benchmark Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  run_benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: boa-dev/criterion-compare-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
